### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by bjsi** [Hookyns/linqy#1]
Is this still a work in progress? The examples in the README got me very interested :).

**Comment by Hookyns** [comment]
Hello @bjsi,
yes it is still in progress but suspended cuz of other projects, but related to this project (tst-reflect, tst-expression).

TL;DR;
>I'm gonna rework the tst-expression, it'll be probably plugin for reworked tst-reflect => expressions with type metadata. 😮 
>
>The tst-expression will just capture context (variables and objects used inside expressions) and expression will be string (so no more serialization with huge amount of generated JS) and parsed at runtime by Acorn or by some other parser (maybe I'll write custom parser cuz of size - I need to parse only arrow functions).
> 
> Predecessor of LINQxy is https://github.com/Hookyns/typeorm-linq. It was never completed, but it is (still,.. I hope) working.

**Comment by bjsi** [comment]
ok thanks @Hookyns :) love this ecosystem of projects you are building
